name: Debug APK Builder

on:
  push:
    branches:
      - dev
      - custom
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
      - custom
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleDebug
      
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
    # ID used to access action output
        id: sign_app
        with:
         releaseDirectory: app/build/outputs/apk/debug
         signingKeyBase64: ${{ secrets.KEYSTORE }}
         alias: ${{ secrets.KEY_ALIAS }}
         keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
         keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
      # override default build-tools version (29.0.3) -- optional
         BUILD_TOOLS_VERSION: "30.0.2"
         
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: 'Manager'
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Switch to update branch
        run: git checkout -f update || git switch --discard-changes --orphan update

      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update
          skip_checkout: true
          file_pattern: app/build/outputs/apk/debug/*signed.apk 
          commit_message: Update Apk
